# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Lang.create(name: 'Русский', min: 'ru', code: '643')
Lang.create(name: 'English', min: 'en', code: '840')
Lang.create(name: 'Germany', min: 'de', code: '276')
# => fields User Status
UserStatus.create(name: 'unregistered')
UserStatus.create(name: 'registered')
UserStatus.create(name: 'blocked')
UserStatus.create(name: 'activated')
UserStatus.create(name: 'suspicious')
UserStatus.create(name: 'administrator')
UserStatus.create(name: 'manager')
# => Input fields User
UserMetumValue.create(name: 'nickname')
UserMetumValue.create(name: 'first_name')
UserMetumValue.create(name: 'last_name')
UserMetumValue.create(name: 'country')
UserMetumValue.create(name: 'city')
UserMetumValue.create(name: 'street')
UserMetumValue.create(name: 'House_apartment')
UserMetumValue.create(name: 'phone')
UserMetumValue.create(name: 'passport_number')
UserMetumValue.create(name: 'date_of_issue')
UserMetumValue.create(name: 'file_passport')
UserMetumValue.create(name: 'payment_pin')
# => Payment system name
PaymentSystem.create(name: 'Bitcoin')
PaymentSystem.create(name: 'Advcash')
PaymentSystem.create(name: 'Payeer')
PaymentSystem.create(name: 'Payza')
PaymentSystem.create(name: 'Perfect Money')
# => Payment meta pay
# => value = примерный курс в евро
PaymentMetum.create(payment_system_id: 1, name: "Bitcoin payment key", value: "990")
PaymentMetum.create(payment_system_id: 3, name: "Advcash payment login", value: "1")
PaymentMetum.create(payment_system_id: 3, name: "Payeer payment login", value: "1")
PaymentMetum.create(payment_system_id: 3, name: "Payza payment login", value: "1")
PaymentMetum.create(payment_system_id: 3, name: "Perfect Money payment login", value: "1")
# => Payment value + / -
PaymentValue.create(name: 'debit')
PaymentValue.create(name: 'credit')
# => Payment Statys 
PaymentStaty.create(name: 'verification')
PaymentStaty.create(name: 'Rejected')
PaymentStaty.create(name: 'Approved')
# => Statistics Meta
StatisticMetum.create(name: 'login')
StatisticMetum.create(name: 'login_wrong')
StatisticMetum.create(name: 'Approved')
StatisticMetum.create(name: 'login_recover')
StatisticMetum.create(name: 'debit_payment_verification')
StatisticMetum.create(name: 'debit_payment_Rejected')
StatisticMetum.create(name: 'debit_payment_Approved')
StatisticMetum.create(name: 'credit_payment_verification')
StatisticMetum.create(name: 'credit_payment_Rejected')
StatisticMetum.create(name: 'credit_payment_Approved')
# => Rates
Rate.create(name: 'seven_days')
Rate.create(name: 'thirty_days')
# => RatesMeta
# => Время ожидания
# => Минимальный взнос
# => Максимальный взнос
# => тавка в % в день
RateMetum.create(name: 'time')
RateMetum.create(name: 'min_deposit')
RateMetum.create(name: 'max_deposit')
RateMetum.create(name: 'rate')
# Post
Post.create(id: 1, href: "first")
Post.create(id: 2, href: "2post")
Post.create(id: 3, href: "3post")
PostMetum.create(post_id: '1', title: 'Заголовок первого поста', summary: 'Краткое описание первого тестового поста',body: '<p> Разнообразный и богатый опыт консультация с широким активом требуют от нас анализа дальнейших направлений развития. Товарищи! реализация намеченных плановых заданий позволяет выполнять важные задания по разработке новых предложений. Равным образом укрепление и развитие структуры влечет за собой процесс внедрения и модернизации дальнейших направлений развития. Идейные соображения высшего порядка, а также укрепление и развитие структуры позволяет оценить значение соответствующий условий активизации. </p><p> Разнообразный и богатый опыт консультация с широким активом способствует подготовки и реализации системы обучения кадров, соответствует насущным потребностям. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение нашей деятельности играет важную роль в формировании форм развития. </p>', lang_id:'1')
PostMetum.create(post_id: '2', title: 'Заголовок Второго поста', summary: 'Краткое описание второго тестового поста',body: '<p>Разнообразный и богатый опыт постоянное информационно-пропагандистское обеспечение нашей деятельности требуют определения и уточнения систем массового участия. Значимость этих проблем настолько очевидна, что постоянный количественный рост и сфера нашей активности играет важную роль в формировании систем массового участия. Равным образом дальнейшее развитие различных форм деятельности играет важную роль в формировании дальнейших направлений развития. Разнообразный и богатый опыт новая модель организационной деятельности требуют от нас анализа существенных финансовых и административных условий. </p>', lang_id:'1')
PostMetum.create(post_id: '3', title: 'Заголовок третьего поста', summary: 'Краткое описание третьего тестового поста',body: '<p>Не следует, однако забывать, что новая модель организационной деятельности влечет за собой процесс внедрения и модернизации модели развития. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение нашей деятельности требуют от нас анализа систем массового участия. Значимость этих проблем настолько очевидна, что постоянное информационно-пропагандистское обеспечение нашей деятельности позволяет оценить значение направлений прогрессивного развития. Идейные соображения высшего порядка, а также постоянный количественный рост и сфера нашей активности в значительной степени обуславливает создание модели развития. Задача организации, в особенности же дальнейшее развитие различных форм деятельности влечет за собой процесс внедрения и модернизации позиций, занимаемых участниками в отношении поставленных задач.</p>', lang_id:'1')
PostMetum.create(post_id: '1', title: 'Title of the first post', summary: 'Brief description of the first test post',body: '<p> A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.</p>', lang_id:'2')
PostMetum.create(post_id: '2', title: 'Title of the 2 post', summary: 'Brief description of the 2 test post',body: '<p> A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.</p>', lang_id:'2')
PostMetum.create(post_id: '3', title: 'Title of the 3 post', summary: 'Brief description of the 3 test post',body: '<p> A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.</p>', lang_id:'2')
PostMetum.create(post_id: '1', title: 'Titel der erste Beitrag', summary: 'Kurzbeschreibung der ersten Test Post',body: '<p>aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.</p>', lang_id:'3')
PostMetum.create(post_id: '2', title: 'Titel der erste Beitrag', summary: 'Kurzbeschreibung der ersten Test Post',body: '<p>aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.</p>', lang_id:'3')
PostMetum.create(post_id: '3', title: 'Titel der erste Beitrag', summary: 'Kurzbeschreibung der ersten Test Post',body: '<p>aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.</p>', lang_id:'3')
# Pages
Page.create(id: 1, href: "Contacts")
Page.create(id: 2, href: "company")
Page.create(id: 3, href: "rates")
PageMetum.create(page_id: 1,lang_id: 1,title: 'Контакты', summary: 'Контакты нашей компании.',text: '<div about="/contact/edinburgh" typeof="sioc:Item foaf:Document" class="ds-1col node node-office contextual-links-region view-mode-contact  clearfix"><div class="map"><img src="http://maps.googleapis.com/maps/api/staticmap?center=55.9438412,-3.1933936&amp;zoom=16&amp;size=600x300&amp;sensor=false&amp;markers=55.9438412,-3.1933936" alt=""></div><div class="field field-name-title field-type-ds field-label-hidden"><div class="field-items"><div class="field-item even" property="dc:title"><h3>Edinburgh</h3></div></div></div><div class="field field-name-field-contact-details field-type-text-long field-label-hidden"><span class="icon"><i class="icon-location"></i></span><div class="field-items"><p>Quartermile Two</p><p>2 Lister Square</p><p>Edinburgh</p><p>EH3 9GL</p><p><a href="/sites/files/edinburgh_map-morton_fraser_office.pdf" target="_blank">Download local directions to the office</a> [PDF]</p></div></div><div class="field field-name-field-google-directions field-type-link-field field-label-hidden"><div class="field-items"><div class="field-item even"><a href="https://www.google.co.uk/maps/place/Morton+Fraser/@55.9438141,-3.1955419,17z/data=!3m1!4b1!4m5!3m4!1s0x4887c79b58382f1f:0x1cfc0d867b011f6a!8m2!3d55.9438141!4d-3.1933532">Get directions</a></div></div></div><div class="field field-name-field-phone-number field-type-text field-label-hidden"><span class="icon"><i class="icon-phone"></i></span><div class="field-items"><p class="rTapNumber187279">0131 247 1000</p></div></div><div class="field field-name-field-fax-number field-type-text field-label-hidden"><span class="icon"><i class="icon-fax"></i></span><div class="field-items">0131 247 1007</div></div><div class="field field-name-field-email-address field-type-email field-label-hidden"><span class="icon"><i class="icon-mail"></i></span><div class="field-items"><a href="mailto:infodesk@skyx-invest.com">infodesk@skyx-invest.com</a></div></div></div>')
PageMetum.create(page_id: 1,lang_id: 2,title: 'Contacts', summary: 'Contacts of our company.',text: '<div about="/contact/edinburgh" typeof="sioc:Item foaf:Document" class="ds-1col node node-office contextual-links-region view-mode-contact  clearfix"><div class="map"><img src="http://maps.googleapis.com/maps/api/staticmap?center=55.9438412,-3.1933936&amp;zoom=16&amp;size=600x300&amp;sensor=false&amp;markers=55.9438412,-3.1933936" alt=""></div><div class="field field-name-title field-type-ds field-label-hidden"><div class="field-items"><div class="field-item even" property="dc:title"><h3>Edinburgh</h3></div></div></div><div class="field field-name-field-contact-details field-type-text-long field-label-hidden"><span class="icon"><i class="icon-location"></i></span><div class="field-items"><p>Quartermile Two</p><p>2 Lister Square</p><p>Edinburgh</p><p>EH3 9GL</p><p><a href="/sites/files/edinburgh_map-morton_fraser_office.pdf" target="_blank">Download local directions to the office</a> [PDF]</p></div></div><div class="field field-name-field-google-directions field-type-link-field field-label-hidden"><div class="field-items"><div class="field-item even"><a href="https://www.google.co.uk/maps/place/Morton+Fraser/@55.9438141,-3.1955419,17z/data=!3m1!4b1!4m5!3m4!1s0x4887c79b58382f1f:0x1cfc0d867b011f6a!8m2!3d55.9438141!4d-3.1933532">Get directions</a></div></div></div><div class="field field-name-field-phone-number field-type-text field-label-hidden"><span class="icon"><i class="icon-phone"></i></span><div class="field-items"><p class="rTapNumber187279">0131 247 1000</p></div></div><div class="field field-name-field-fax-number field-type-text field-label-hidden"><span class="icon"><i class="icon-fax"></i></span><div class="field-items">0131 247 1007</div></div><div class="field field-name-field-email-address field-type-email field-label-hidden"><span class="icon"><i class="icon-mail"></i></span><div class="field-items"><a href="mailto:infodesk@skyx-invest.com">infodesk@skyx-invest.com</a></div></div></div>')
PageMetum.create(page_id: 1,lang_id: 3,title: 'Kontakte', summary: 'Kontaktieren Sie unser Unternehmen.',text: '<div about="/contact/edinburgh" typeof="sioc:Item foaf:Document" class="ds-1col node node-office contextual-links-region view-mode-contact  clearfix"><div class="map"><img src="http://maps.googleapis.com/maps/api/staticmap?center=55.9438412,-3.1933936&amp;zoom=16&amp;size=600x300&amp;sensor=false&amp;markers=55.9438412,-3.1933936" alt=""></div><div class="field field-name-title field-type-ds field-label-hidden"><div class="field-items"><div class="field-item even" property="dc:title"><h3>Edinburgh</h3></div></div></div><div class="field field-name-field-contact-details field-type-text-long field-label-hidden"><span class="icon"><i class="icon-location"></i></span><div class="field-items"><p>Quartermile Two</p><p>2 Lister Square</p><p>Edinburgh</p><p>EH3 9GL</p><p><a href="/sites/files/edinburgh_map-morton_fraser_office.pdf" target="_blank">Download local directions to the office</a> [PDF]</p></div></div><div class="field field-name-field-google-directions field-type-link-field field-label-hidden"><div class="field-items"><div class="field-item even"><a href="https://www.google.co.uk/maps/place/Morton+Fraser/@55.9438141,-3.1955419,17z/data=!3m1!4b1!4m5!3m4!1s0x4887c79b58382f1f:0x1cfc0d867b011f6a!8m2!3d55.9438141!4d-3.1933532">Get directions</a></div></div></div><div class="field field-name-field-phone-number field-type-text field-label-hidden"><span class="icon"><i class="icon-phone"></i></span><div class="field-items"><p class="rTapNumber187279">0131 247 1000</p></div></div><div class="field field-name-field-fax-number field-type-text field-label-hidden"><span class="icon"><i class="icon-fax"></i></span><div class="field-items">0131 247 1007</div></div><div class="field field-name-field-email-address field-type-email field-label-hidden"><span class="icon"><i class="icon-mail"></i></span><div class="field-items"><a href="mailto:infodesk@skyx-invest.com">infodesk@skyx-invest.com</a></div></div></div>')
PageMetum.create(page_id: 2,lang_id: 1,title: 'О Компании', summary: 'Краткая информация о нашей компании.',text: '<h2>О чем на самом деле должна рассказывать страница «О компании»</h2><p>Думаете, текст «О нас» — это едва ли не единственное место на корпоративном сайте и в интернете в целом, где можно нахваливать себя, хвастаться, писать о своих достижениях, лучших качествах? Да кому они нужны, ваши качества. Все эти «мы», «наша компания», «стремимся заботиться», «удовлетворяем индивидуально», «засыпаем и просыпаемся с мыслями о клиенте» и прочая ерунда никого не интересует. Клиентам наплевать на вашу динамично-профессиональную команду, особенно, когда они впервые попадают на сайт. Они интересуется своим бизнесом, своей выгодой, решением своих задач, своим молодым коллективом. </p><p>Страница «О компании» не должна рассказывать о вашей компании. Посетитель должен найти здесь информацию о себе, о своих интересах и потребностях. Он должен узнать, как вы решите его проблемы и почему вы обязательно это сделаете. Создавая страницу «О нас», помните: на самом деле она называется «О вас». О них: любимых, желанных, лояльных, капризных, щедрых, экономных клиентах. </p>')
PageMetum.create(page_id: 2,lang_id: 2,title: 'About company', summary: 'Brief information about our company.',text:'<h2>O chem na samom dele dolzhna rasskazyvat stranitsa «O kompanii»</h2><p>Dumayete, tekst «O nas» — eto yedva li ne yedinstvennoye mesto na korporativnom sayte i v internete v tselom, gde mozhno nakhvalivat sebya, khvastat sya, pisat  o svoikh dostizheniyakh, luchshikh kachestvakh? Da komu oni nuzhny, vashi kachestva. Vse eti «my», «nasha kompaniya», «stremimsya zabotit sya», «udovletvoryayem individual no», «zasypayem i prosypayemsya s myslyami o kliyente» i prochaya yerunda nikogo ne interesuyet. Kliyentam naplevat  na vashu dinamichno-professional nuyu komandu, osobenno, kogda oni vpervyye popadayut na sayt. Oni interesuyetsya svoim biznesom, svoyey vygodoy, resheniyem svoikh zadach, svoim molodym kollektivom. </p><p>Stranitsa «O kompanii» ne dolzhna rasskazyvat  o vashey kompanii. Posetitel  dolzhen nayti zdes  informatsiyu o sebe, o svoikh interesakh i potrebnostyakh. On dolzhen uznat , kak vy reshite yego problemy i pochemu vy obyazatel no eto sdelayete. Sozdavaya stranitsu «O nas», pomnite: na samom dele ona nazyvayetsya «O vas». O nikh: lyubimykh, zhelannykh, loyal nykh, kapriznykh, shchedrykh, ekonomnykh kliyentakh. </p></ H2> <p> Think, the text "About Us" is almost the only place on the corporate website and on the Internet as a whole where you can praise yourself, Boast, write about their achievements, best qualities? Yes to whom they are needed, your qualities. All these "we", "our company", "we strive to take care of", "satisfy individually", "fall asleep and wake up with thoughts about the client" and other nonsense does not interest anyone. Customers do not care about your dynamic professional team, especially when they first enter the site. They are interested in their business, their benefits, their tasks, their young team. </ P> <p> The "About the Company" page should not tell about your company. The visitor should find here information about himself, his interests and needs. He must find out how you solve his problems and why you will necessarily do it. Creating a page "About Us", remember: in fact it is called "About You". About them: favorite, desired, loyal, capricious, generous, thrifty customers. </ P>')
PageMetum.create(page_id: 2,lang_id: 3,title: 'Über uns', summary: 'Kurze Informationen über unsere Firma.',text:'<H2> Was sollte wirklich Seite „Über uns» </ h2> <p> Denken Sie, den Text ‚Über uns‘ sprechen - das ist vielleicht der einzige Ort auf der Unternehmens-Website und das Internet im Allgemeinen, wo es möglich ist, sich selbst zu verherrlichen, prahlt, schreibt über seine Leistungen, bessere Qualität? Aber wer braucht sie Geld. Alle diese „wir“, „unser Unternehmen“, „suchen Pflege“, „das Individuum gerecht zu werden“, „wir und über den Kunden“ und solche Sachen kümmert sich niemand denken aufwachen schlafen gehen. Kunden, kümmern sich nicht um Ihre dynamischen, professionellen Team, vor allem, wenn sie auf die Website an erster Stelle. Sie interessieren sich für Ihr Unternehmen, Ihre Gewinne, ihre Probleme zu lösen, ihre junge Mannschaft. </ P> <p> Seite „Über uns“ sollte nicht über Ihr Unternehmen sprechen. Der Besucher sollte die Informationen über sich selbst, Ihre Interessen und Bedürfnisse finden. Er muss lernen, wie Sie mit Problem wählen und warum Sie es tun. Durch die Schaffung einer Seite „Über uns“, denken Sie daran: in der Tat ist es das genannte „Lasse dich kennenlernen.“ Über sie: geliebt, gehegt, treu, wunderlich, großzügig, sparsame Kunden. </ P> ')
PageMetum.create(page_id: 3,lang_id: 1,title: 'Тарифы', summary: 'Тарифы и фклады.',text:'<h2>Выгодные ставки – наша традиция</h2><p></p><p>Вклад «Проценты в рост» – вклад с пополнением со ставкой до 9% годовых.</p><p>Вклад «Мой доход» – классический вклад со ставкой до 8% годовых.</p><p>Вклад «Максимум возможностей» – приходно-расходный вклад со ставкой до 7,5% годовых.</p><p></p><p></p><p>Специальные условия в валюте! Вклад «Моя выгода» – классический вклад со ставкой до 1,7% годовых в долларах и до 0,3% годовых в евро.</p><p></p><p>Подобрать офис</p><p>Проценты в рост</p><p></p><p>Вклад с пополнением и льготными условиями досрочного расторжения</p><p></p><p>    Максимальная ставка – до 9% годовых в рублях.</p><p>    Возможность пополнения вклада в первые 60 дней.</p><p>    Сохранение процентов при досрочном расторжении вклада.</p><p></p><p>Узнать подробнее</p><p>Мой доход</p><p></p><p>Вклад без возможности пополнения и расходных операций</p><p></p><p>    Ваш доход – до 8% годовых в рублях.</p><p>    Льготная ставка при досрочном расторжении.</p><p>    Удобный срок размещения - 3, 6 и 12 месяцев.</p><p>Узнать подробнее</p><p>Максимум возможностей</p><p></p><p>Пополнение и снятие без потери процентов</p><p></p><p></p><p>    До 7,5% годовых в рублях. Зафиксируйте выгодную ставку на один или два года!</p><p>    Возможность пополнения и расходных операций без потери процентов.</p><p>    Онлайн-вклад «Максимум возможностей - Безлимитный» с фиксированной ставкой 6,85% годовых в рублях.</p><p></p>')
PageMetum.create(page_id: 3,lang_id: 2,title: 'Rates', summary: 'Tariffs and flags.',text:'<H2> Profitable rates are our tradition </ h2> <p> </ p> <p> Deposit "Interest in Growth" is a deposit with a replenishment with a rate of up to 9% per annum. </ P> <p> "- a classical deposit with a rate of up to 8% per annum. </ P> <p> The" Maximum Opportunity "contribution is a cash flow account with a rate of up to 7.5% per annum. </ P> <p> </ p> <p > </ P> <p> Special conditions in currency! The "My Profit" deposit is a classic deposit with a rate of up to 1.7% per annum in dollars and up to 0.3% per annum in euros. </ P> <p> </ p> <p> Pick an office </ p> <p > Interest in growth </ p> <p> </ p> <p> Deposit with replenishment and preferential terms of early termination </ p> <p> </ p> <p> The maximum rate - up to 9% per annum in rubles. </ P> <p> The possibility of replenishment of the deposit in the first 60 days. </ P> <p> Preservation of interest on early termination of the deposit. </ P> <p> </ p> <p> Learn more </ p> <p> P> My income </ p> <p> </ p> <p> Deposit without the possibility of replenishment and spending operations </ p> <p> </ p> <p> Your income - up to 8% per annum in rubles. < / P> <p> Preferential rate At early termination. </ P> <p> A convenient placement period is 3, 6 and 12 months. </ P> <p> Learn more </ p> <p> Maximum Opportunity </ p> <p> </ p > <P> Deposit and withdrawal without loss of interest </ p> <p> </ p> <p> </ p> <p> Up to 7.5% per annum in rubles. Fix a favorable rate for one or two years! </ P> <p> The possibility of replenishment and spending operations without loss of interest. </ P> <p> Online deposit "Maximum Opportunity - Unlimited" with a fixed rate of 6.85% per annum in Rubles. </ P> <p> </ p>')
PageMetum.create(page_id: 3,lang_id: 3,title: 'Tarife', summary: 'Tarife und fklady.',text:'<H2> günstige Preise - unsere Tradition </ h2> <p> </ p> <p> Deposit "Das Interesse an Wachstum" - eine Einzahlung mit Nachschub in Höhe von 9% pa </ p> <p> Deposit „Mein Einkommen. "- ein klassischer Beitrag in Höhe von 8% pa </ p> <p> der Beitrag" Viele Möglichkeiten. „- Kredit- und Debit Beitrag in Höhe von 7,5% pro Jahr </ p> <p> </ p> <p. > </ p> <p> Besondere Bedingungen in der Währung! Beitrag "Mein Vorteil" - ein klassischer Beitrag in Höhe von 1,7% pro Jahr in US-Dollar und 0,3% in dem Euro </ p> <p> </ p> <p> Wählen Sie das Büro </ p> <p. > Das Interesse an Wachstum </ p> <p> </ p> <p> der Beitrag zur Auffüllung und günstigen Bedingungen der vorzeitigen Beendigung </ p> <p> </ p> <p> Die maximale Geschwindigkeit - bis zu 9% pro Jahr in Rubel. </ p> <p> die Fähigkeit, die Einzahlung in den ersten 60 Tagen wieder aufzufüllen. </ p> <p> Speichern Prozent für die vorzeitige Beendigung der Ablagerung. </ p> <p> </ p> <p> weitere Informationen </ p> < p> Mein Einkommen </ p> <p> </ p> <p> der Beitrag ohne die Möglichkeit der Wiederauffüllung und Debitkarten-Transaktionen </ p> <p> </ p> <p> Ihr Einkommen - bis zu 8% pro Jahr in Rubel <. / p> <p> Vorzugspreise . Vorzeitige Beendigung </ p> <p> Komfortable Unterkunft Periode - 3, 6 und 12 Monate </ p> <p> Weitere Informationen </ p> <p> Maximize </ p> <p> </ p. > <p> Kaution und Auszahlungen ohne Verlust von Interesse </ p> <p> </ p> <p> </ p> <p> bis zu 7,5% pro Jahr in Rubel. Sichern Sie die beste Wette auf einem oder zwei Jahre </ p> <p> Die Fähigkeit von Interesse zu deponieren und Debitkarten-Transaktionen ohne Verlust </ p> <p> Online-Beitrag „Viele Möglichkeiten - No Limit!“ Fixed Rate von 6,85% pro Jahr. Rubel. </ p> <p> </ p>')



