# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Lang.create(name: 'Русский', min: 'RU', code: '643')
Lang.create(name: 'English', min: 'US', code: '840')
Lang.create(name: 'Germany', min: 'DE', code: '276')
Post.create()
Post.create()
Post.create()
PostMetum.create(post_id: 1, title: 'Заголовок первого поста', summary: 'Краткое описание первого тестового поста',body: '<p> Разнообразный и богатый опыт консультация с широким активом требуют от нас анализа дальнейших направлений развития. Товарищи! реализация намеченных плановых заданий позволяет выполнять важные задания по разработке новых предложений. Равным образом укрепление и развитие структуры влечет за собой процесс внедрения и модернизации дальнейших направлений развития. Идейные соображения высшего порядка, а также укрепление и развитие структуры позволяет оценить значение соответствующий условий активизации. </p><p> Разнообразный и богатый опыт консультация с широким активом способствует подготовки и реализации системы обучения кадров, соответствует насущным потребностям. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение нашей деятельности играет важную роль в формировании форм развития. </p>', lang_id:'1')
PostMetum.create(post_id: 2, title: 'Заголовок Второго поста', summary: 'Краткое описание второго тестового поста',body: '<p>Разнообразный и богатый опыт постоянное информационно-пропагандистское обеспечение нашей деятельности требуют определения и уточнения систем массового участия. Значимость этих проблем настолько очевидна, что постоянный количественный рост и сфера нашей активности играет важную роль в формировании систем массового участия. Равным образом дальнейшее развитие различных форм деятельности играет важную роль в формировании дальнейших направлений развития. Разнообразный и богатый опыт новая модель организационной деятельности требуют от нас анализа существенных финансовых и административных условий. </p>', lang_id:'1')
PostMetum.create(post_id: 3, title: 'Заголовок третьего поста', summary: 'Краткое описание третьего тестового поста',body: '<p>Не следует, однако забывать, что новая модель организационной деятельности влечет за собой процесс внедрения и модернизации модели развития. Задача организации, в особенности же постоянное информационно-пропагандистское обеспечение нашей деятельности требуют от нас анализа систем массового участия. Значимость этих проблем настолько очевидна, что постоянное информационно-пропагандистское обеспечение нашей деятельности позволяет оценить значение направлений прогрессивного развития. Идейные соображения высшего порядка, а также постоянный количественный рост и сфера нашей активности в значительной степени обуславливает создание модели развития. Задача организации, в особенности же дальнейшее развитие различных форм деятельности влечет за собой процесс внедрения и модернизации позиций, занимаемых участниками в отношении поставленных задач.</p>', lang_id:'1')
PostMetum.create(post_id: 1, title: 'Title of the first post', summary: 'Brief description of the first test post',body: '<p> A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.</p>', lang_id:'2')
PostMetum.create(post_id: 2, title: 'Title of the 2 post', summary: 'Brief description of the 2 test post',body: '<p> A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.</p>', lang_id:'2')
PostMetum.create(post_id: 3, title: 'Title of the 3 post', summary: 'Brief description of the 3 test post',body: '<p> A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.A diverse and rich experience of consulting with a broad asset requires us to analyze further areas of development. Comrades! The implementation of the planned targets allows you to perform important tasks for the development of new proposals.</p>', lang_id:'2')
PostMetum.create(post_id: 1, title: 'Titel der erste Beitrag', summary: 'Kurzbeschreibung der ersten Test Post',body: '<p>aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.</p>', lang_id:'3')
PostMetum.create(post_id: 2, title: 'Titel der erste Beitrag', summary: 'Kurzbeschreibung der ersten Test Post',body: '<p>aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.</p>', lang_id:'3')
PostMetum.create(post_id: 3, title: 'Titel der erste Beitrag', summary: 'Kurzbeschreibung der ersten Test Post',body: '<p>aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.aznoobrazny und Erfahrung ständige Information und Propaganda Unterstützung unserer Aktivitäten erfordern die Bestimmung und Verfeinerung der partizipativen Systeme. Die Bedeutung dieser Probleme sind so offensichtlich, dass das ständige quantitative Wachstum und der Umfang unserer Tätigkeit eine wichtige Rolle bei der Bildung von partizipativen Systemen spielen.</p>', lang_id:'3')